<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun = rerun.strip.gsub /\s/, ' '
rerun_opts = rerun.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags 'not @wip and not @accessibility' --publish-quiet --retry 2"
accessibility_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags '@accessibility' --publish-quiet "
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features --publish-quiet
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags 'not @wip'
accessibility: <%= accessibility_opts %> features/accessibility
<% [
  ['supply-teachers', 'supply_teachers', %w[RM6238 RM6376]],
  ['management-consultancy', 'management_consultancy', %w[RM6187 RM6309]],
  ['legal-services', 'legal_services', %w[RM6240]],
  ['legal-panel-for-government', 'legal_panel_for_government', %w[RM6360]],
].each do |service_slug, service_folder, frameworks| %>
<%= service_slug %>: <%= std_opts %> features/services/<%= service_folder %>
<% frameworks.each do |framework| %>
<%= service_slug %>:<%= framework %>: <%= std_opts %> features/services/<%= service_folder %>/<%= framework.downcase %>
<% end %>
<% end %>